EinStack/glide

.golangci.yml
Accidentally, added that linter. In-package tests are far more popular approach in Golang community, so no need to move tests into a sep package.
=> Removed the testpackage linter

codecov.yml
Disable `codecov/patch` job that forces to update code coverage for now.
=> Disable codecov/patch job

Makefile, config.dev.yaml, pkg/cmd/cli.go, pkg/config/provider.go, pkg/config/provider_test.go, pkg/config/testdata/provider.broken.yaml
Handle a special case when the config flag is not passed. We fail in that case as we need to have at least one pool/model configured and we could not default that setup in some useful way.
=> Fail on no config passed

pkg/api/schemas/language.go, pkg/providers/openai/chat.go, pkg/providers/openai/client_test.go
- Updated the Unified schema per the GEP
- Updated the doChatRequest func to marshal openai response into the unified response
- Tested
=> 54 unified response

pkg/api/schemas/language.go, pkg/providers/cohere/chat.go, pkg/providers/openai/chat.go, pkg/providers/openai/config.go
- Updated OpenAI and Cohere so the response is marshaled into each providers given response struct then into the Unified Response
=> 61 update openai client

.github/workflows/lint.yaml, Makefile, docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/providers/clients/config.go, pkg/providers/config.go, pkg/providers/provider.go, pkg/providers/testing.go, pkg/routers/config.go, pkg/routers/config_test.go, pkg/routers/health/error_budget.go, pkg/routers/latency/config.go, pkg/routers/latency/config_test.go, pkg/routers/latency/moving_average.go, pkg/routers/latency/moving_average_test.go, pkg/routers/router_test.go, pkg/routers/routing/least_latency.go, pkg/routers/routing/least_latency_test.go, pkg/routers/routing/moving_average.go, pkg/routers/routing/moving_average_test.go, pkg/routers/routing/priority_test.go, pkg/routers/routing/round_robin.go, pkg/routers/routing/round_robin_test.go
Adding a new routing strategy to pick the least latency model. Adding simple coverage for some config building logic.
=> 🛠️ #46 inited the least latency routing

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/providers/config.go, pkg/providers/provider.go, pkg/providers/testing.go, pkg/routers/config.go, pkg/routers/router_test.go, pkg/routers/routing/priority.go, pkg/routers/routing/priority_test.go, pkg/routers/routing/round_robin_test.go, pkg/routers/routing/weighted_round_robin.go, pkg/routers/routing/weighted_round_robin_test.go
Added weighted round robin routing strategy.
=> 🛠️ #45: Added WRR routing strategy

.github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/vuln.yaml, .goreleaser.yml, Makefile, images/Makefile, images/alpine.Dockerfile, images/distroless.Dockerfile, images/redhat.Dockerfile, images/ubuntu.Dockerfile, pkg/routers/health/buckets.go, pkg/routers/health/buckets_test.go, pkg/routers/health/error_budget.go, pkg/version.go
Implementation of [GEP0004 ](https://github.com/EinStack/geps/pull/7) related to binary & image building workflow.
Changes:
- On tag creation in the main branch, there is a new release workflow that builds and publish binaries and images
- There are four images built for each Glide version with different OS flavours
- Building binaries only for netpoll-compatible OS
- Binaries are attached to a GH release draft
- When the build is done there is an announcement sent to Discord and GH discussions
- Added a basic homebrew tap publishing
=> 👷 #9: Build binaries on tags

README.md, docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/api/http/handlers.go, pkg/api/schemas/language.go, pkg/routers/router.go, pkg/routers/router_test.go
Update the Unified Chat Schema to allow model specification. This allows users to specify different prompts for different models. The correct JSON request is selected after the router has determined the correct model.
=> ✨ #81: Allow to chat message based for specific models

images/Makefile
This is useful for helm charts, so we could use AppVersion param to pull image as default
=> 👷 Create a image tag with pure version (without distro suffix)

.github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/vuln.yaml, Makefile, go.mod, go.sum, images/alpine.Dockerfile, images/distroless.Dockerfile, images/redhat.Dockerfile, images/ubuntu.Dockerfile
Addressing CVEs by upgrading:
- Crypt lib to v0.21.0
- Golang to 1.22.1
- Fiber to v2.52.2
- Disabled govulncheck because of https://github.com/golang/go/issues/65590
=> 🔓 #148 update crypto lib, golang, fiber

pkg/api/http/config_test.go, pkg/config/expander_test.go, pkg/config/testdata/expander.file.notfound.yaml, pkg/config/testdata/expander.file.yaml, pkg/config/testdata/openai_key, pkg/routers/retry/config_test.go, pkg/routers/router.go, pkg/telemetry/logging_test.go, pkg/telemetry/telemetry_test.go
Improve general coverage of the codebase:
- covered a few configs by tests
- file content expansion in configurations
=> #146: Covered the telemetry by tests

pkg/api/http/handlers.go, pkg/api/schemas/chat.go, pkg/api/schemas/chat_stream.go, pkg/providers/anthropic/chat_stream.go, pkg/providers/azureopenai/chat_stream.go, pkg/providers/bedrock/chat_stream.go, pkg/providers/cohere/chat_stream.go, pkg/providers/lang.go, pkg/providers/octoml/chat_stream.go, pkg/providers/ollama/chat_stream.go, pkg/providers/openai/chat.go, pkg/providers/openai/chat_stream.go, pkg/providers/openai/chat_stream_test.go, pkg/providers/testing/lang.go, pkg/routers/router.go, pkg/routers/router_test.go
- Separated chat & chat stream request schemas 
- introduced a new finish reason field 
- added metadata to stream chat response
- allow to attach some metadata to a chat stream request and then attach it to each chat stream chunk
- adjusted error message schema to include request ID and metadata
=> 🔧 #161: Refined the chat stream req/responses

pkg/gateway.go, pkg/providers/anthropic/chat.go, pkg/providers/anthropic/client.go, pkg/providers/anthropic/errors.go, pkg/providers/azureopenai/chat.go, pkg/providers/azureopenai/client.go, pkg/providers/azureopenai/client_test.go, pkg/providers/azureopenai/errors.go, pkg/providers/clients/errors.go, pkg/providers/cohere/chat.go, pkg/providers/lang.go, pkg/providers/octoml/chat.go, pkg/providers/octoml/client.go, pkg/providers/octoml/client_test.go, pkg/providers/octoml/errors.go, pkg/providers/openai/errors.go, pkg/routers/health/tracker.go, pkg/routers/router.go
Handle a wrong API key case to make the model as unavailable permanently
=> ✨ #170 Handle unauthorized error in health tracker

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/api/schemas/chat.go, pkg/providers/anthropic/chat.go, pkg/providers/anthropic/client.go, pkg/providers/anthropic/config.go, pkg/providers/anthropic/schamas.go, pkg/providers/anthropic/testdata/chat.success.json, pkg/providers/bedrock/chat.go, pkg/providers/cohere/schemas.go, pkg/providers/lang.go, pkg/providers/ollama/chat.go, pkg/providers/openai/schemas.go
Anthropic seems to go out of beta finally and I could get a token to test our integration which doesn't seem to work because of the wrong API key header used.
- Fixed the header where Anthropic API key is passed
- Started propagating token usage of Anthropic requests
- Corrected the TokenUsage interface by changing count field to integers from floats
=> ✨🐛 #183: Fix Anthropic API key header and start counting its token usage

pkg/api/schemas/chat.go, pkg/api/schemas/chat_stream.go, pkg/providers/azureopenai/chat.go, pkg/providers/azureopenai/chat_stream.go, pkg/providers/azureopenai/chat_stream_test.go, pkg/providers/azureopenai/client.go, pkg/providers/azureopenai/schemas.go, pkg/providers/azureopenai/testdata/chat_stream.empty.txt, pkg/providers/azureopenai/testdata/chat_stream.nodone.txt, pkg/providers/azureopenai/testdata/chat_stream.success.txt, pkg/providers/openai/chat.go
- Added streaming support
- Refactor chat.go per latest changes
- Refactor client.go
- Add schemas.go
=> ✨ #173: Add Streaming Support for Azure OpenAI

pkg/config/fields/duration.go, pkg/providers/lang.go, pkg/providers/provider.go, pkg/providers/testing/models.go, pkg/routers/latency/config.go, pkg/routers/routing/least_latency.go
Rendering Durations as strings rather than nanosecond integers:
=> 🔧 #186: Rendering Durations in a human-friendly way

pkg/api/http/handlers.go, pkg/api/schemas/chat_stream.go, pkg/providers/azureopenai/chat_stream.go, pkg/providers/cohere/chat.go, pkg/providers/cohere/chat_stream.go, pkg/providers/cohere/finish_reason.go, pkg/providers/lang.go, pkg/providers/openai/chat.go, pkg/providers/openai/chat_stream.go, pkg/providers/openai/client.go, pkg/providers/openai/finish_reasons.go, pkg/providers/testing/lang.go, pkg/routers/router.go, pkg/routers/router_test.go, pkg/telemetry/telemetry.go
- Passed RouterID and ModelID information in the chat stream messages
- Introduced a new ChatStreamMessage type that joins both chunk and error messages. Removed unneeded context from provider chatStream structs
- defined a set of possible error codes during chat streaming
- started simplifying logging by using context-based loggers
- Introduced finish_reason on the error schema
https://github.com/EinStack/glide/assets/9402690/d09334be-23ac-46dc-a869-dc2e6653976b
=> 🔧 #195 #196: Set router ctx in stream chunks & handle end of stream in case of some errors

.github/workflows/activity-notifications.yaml
Creating a development notification stream across all repositories in Discord
=> 👷‍♂️ Added a new GH action to watch for glide activity stream

go.mod, go.sum, pkg/telemetry/telemetry.go
=> 🔧 #221 Add B3 propagator

docs/docs.go, docs/swagger.json, docs/swagger.yaml, pkg/providers/anthropic/client.go, pkg/providers/azureopenai/client.go, pkg/providers/bedrock/client.go, pkg/providers/clients/config.go, pkg/providers/clients/config_test.go, pkg/providers/cohere/client.go, pkg/providers/octoml/client.go, pkg/providers/ollama/client.go, pkg/providers/openai/client.go
Make client connection pool configuration configurable from Glide's config:
#164
=> 🔧 #164 Make client connection pool configurable across all providers

pkg/telemetry/telemetry.go, pkg/telemetry/telemetry_test.go
fixes #248
This commit adds fallback exporters to autoexport. Ensuring spans and metrics are disabled.
A unit test is included to ensure we use the correct exporters.
=> 🔧 #248 Disable span and metrics by default

pkg/providers/anthropic/config.go, pkg/providers/azureopenai/config.go, pkg/providers/bedrock/config.go, pkg/providers/cohere/config.go, pkg/providers/octoml/config.go, pkg/providers/ollama/config.go, pkg/providers/openai/chat.go, pkg/providers/openai/config.go
Convert all camelCase config fields to the snake_case in the provider configs
=> 💥 Convert all camelCase config fields to the snake_case in the provider configs

pkg/api/schemas/chat.go
Removing `omitempty` fields from chat response per request.
Closes #266
=> #266: removing omitempty from response definition

.air.toml, Makefile
Adds a basic .air.toml file to support using Air for live reloading
Fixes #240
=> 🔧 Adds support for Air live reloading
